
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button button1_1;

	private global::Gtk.Button button1_2;

	private global::Gtk.Button button1_3;

	private global::Gtk.Button button2_1;

	private global::Gtk.Button button2_2;

	private global::Gtk.Button button2_3;

	private global::Gtk.Button button3_1;

	private global::Gtk.Button button3_2;

	private global::Gtk.Button button3_3;

	private global::Gtk.Image image2;

	private global::Gtk.Label winnerLabel;

	private global::Gtk.Label playerLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 350;
		this.HeightRequest = 250;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("TicTacToe - AndrewNation");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-execute", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.DefaultWidth = 350;
		this.DefaultHeight = 300;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1_1 = new global::Gtk.Button();
		this.button1_1.WidthRequest = 35;
		this.button1_1.HeightRequest = 35;
		this.button1_1.CanFocus = true;
		this.button1_1.Name = "button1_1";
		this.button1_1.UseUnderline = true;
		this.button1_1.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button1_1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1_1]));
		w1.X = 10;
		w1.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1_2 = new global::Gtk.Button();
		this.button1_2.WidthRequest = 35;
		this.button1_2.HeightRequest = 35;
		this.button1_2.CanFocus = true;
		this.button1_2.Name = "button1_2";
		this.button1_2.UseUnderline = true;
		this.button1_2.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button1_2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1_2]));
		w2.X = 59;
		w2.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1_3 = new global::Gtk.Button();
		this.button1_3.WidthRequest = 35;
		this.button1_3.HeightRequest = 35;
		this.button1_3.CanFocus = true;
		this.button1_3.Name = "button1_3";
		this.button1_3.UseUnderline = true;
		this.button1_3.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button1_3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1_3]));
		w3.X = 108;
		w3.Y = 52;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2_1 = new global::Gtk.Button();
		this.button2_1.WidthRequest = 35;
		this.button2_1.HeightRequest = 35;
		this.button2_1.CanFocus = true;
		this.button2_1.Name = "button2_1";
		this.button2_1.UseUnderline = true;
		this.button2_1.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button2_1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2_1]));
		w4.X = 10;
		w4.Y = 102;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2_2 = new global::Gtk.Button();
		this.button2_2.WidthRequest = 35;
		this.button2_2.HeightRequest = 35;
		this.button2_2.CanFocus = true;
		this.button2_2.Name = "button2_2";
		this.button2_2.UseUnderline = true;
		this.button2_2.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button2_2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2_2]));
		w5.X = 59;
		w5.Y = 102;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button2_3 = new global::Gtk.Button();
		this.button2_3.WidthRequest = 35;
		this.button2_3.HeightRequest = 35;
		this.button2_3.CanFocus = true;
		this.button2_3.Name = "button2_3";
		this.button2_3.UseUnderline = true;
		this.button2_3.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button2_3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2_3]));
		w6.X = 108;
		w6.Y = 102;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3_1 = new global::Gtk.Button();
		this.button3_1.WidthRequest = 35;
		this.button3_1.HeightRequest = 35;
		this.button3_1.CanFocus = true;
		this.button3_1.Name = "button3_1";
		this.button3_1.UseUnderline = true;
		this.button3_1.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button3_1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3_1]));
		w7.X = 10;
		w7.Y = 151;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3_2 = new global::Gtk.Button();
		this.button3_2.WidthRequest = 35;
		this.button3_2.HeightRequest = 35;
		this.button3_2.CanFocus = true;
		this.button3_2.Name = "button3_2";
		this.button3_2.UseUnderline = true;
		this.button3_2.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button3_2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3_2]));
		w8.X = 59;
		w8.Y = 151;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button3_3 = new global::Gtk.Button();
		this.button3_3.WidthRequest = 35;
		this.button3_3.HeightRequest = 35;
		this.button3_3.CanFocus = true;
		this.button3_3.Name = "button3_3";
		this.button3_3.UseUnderline = true;
		this.button3_3.Label = global::Mono.Unix.Catalog.GetString("-");
		this.fixed1.Add(this.button3_3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button3_3]));
		w9.X = 108;
		w9.Y = 151;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image2 = new global::Gtk.Image();
		this.image2.WidthRequest = 100;
		this.image2.HeightRequest = 100;
		this.image2.CanDefault = true;
		this.image2.Name = "image2";
		this.image2.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "stock_smiley-15", global::Gtk.IconSize.Menu);
		this.fixed1.Add(this.image2);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image2]));
		w10.X = 146;
		w10.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.winnerLabel = new global::Gtk.Label();
		this.winnerLabel.Name = "winnerLabel";
		this.winnerLabel.LabelProp = global::Mono.Unix.Catalog.GetString("---");
		this.fixed1.Add(this.winnerLabel);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.winnerLabel]));
		w11.X = 13;
		w11.Y = 24;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.playerLabel = new global::Gtk.Label();
		this.playerLabel.Name = "playerLabel";
		this.playerLabel.LabelProp = global::Mono.Unix.Catalog.GetString("SUA VEZ");
		this.fixed1.Add(this.playerLabel);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.playerLabel]));
		w12.X = 167;
		w12.Y = 104;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button1_1.Clicked += new global::System.EventHandler(this.OnButton11Clicked);
		this.button1_2.Clicked += new global::System.EventHandler(this.OnButton12Clicked);
		this.button1_3.Clicked += new global::System.EventHandler(this.OnButton13Clicked);
		this.button2_1.Clicked += new global::System.EventHandler(this.OnButton21Clicked);
		this.button2_2.Clicked += new global::System.EventHandler(this.OnButton22Clicked);
		this.button2_3.Clicked += new global::System.EventHandler(this.OnButton23Clicked);
		this.button3_1.Clicked += new global::System.EventHandler(this.OnButton31Clicked);
		this.button3_2.Clicked += new global::System.EventHandler(this.OnButton32Clicked);
		this.button3_3.Clicked += new global::System.EventHandler(this.OnButton33Clicked);
	}
}
